[Interface]
PrivateKey = OB4ZpjDiiknudmdXuUMd8qgRMTlh1HD/Wb0xshf311c=
Address = 10.5.5.2/32
DNS = 10.5.5.1

[Peer]
PublicKey = mtz2Cz7j8tlFKh5x7yzowR8NpGfL+dyA3NR3REriwwU=
PresharedKey = ga6YBcB9cLpIrKcGAc1ffrW2ywWoRU9b99l+ubmPQO8=
AllowedIPs = 0.0.0.0/0
Endpoint = 41.71.6.230:51820
PersistentKeepalive = 25

